# rustfmt.toml
# web description of options: https://rust-lang.github.io/rustfmt/?version=v1.6.0&search=

# required_version         # specify rustfmt version requirement
# ignore = []              # files for rustfmt to ignore
tab_spaces = 8                     # legible groups! :)

# # format_strings = true        # auto line-break strings (easier to read, more annoying to edit)
#
# brace_style = "PreferSameLine" # braces start on line of what they connect to
# chain_width = 0                # default: 60
# indent_style = "visual" # nests inline with thing needing verticality
#
# imports_granularity = "Crate"     # group all imports for a crate together
# group_imports = "StdExternalCrate" # category style grouping of imports (ala isort in python)
# struct_field_align_threshold = 20  # move distance to seek type alignment in struct fields
#
# reorder_impl_items = true      # assoc_type & const at top of impl
# use_field_init_shorthand = true # let _ = some_struct {x, y, z}
# where_single_line = true        # where on single line if few types
#
# inline_attribute_width=50    # distance to allow attributes on same lines a what they tag
# # overflow_delimited_expr = true # no double nesting for verticle formatted lists, etc.
# type_punctuation_density = "Compressed"  # no spaces around (e.g.) TypeA+TypeB
